spring:
    application:
        name: demo
    datasource:
        url: jdbc:mysql://localhost:3306/cyclist?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
            map-underscore-to-camel-case: true
